### ISSUE TITLE
ci for getting started with dapp-offer-up, docker-compose

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/dapp-offer-up#48]
This issue is related to https://github.com/Agoric/agoric-sdk/issues/8381 but not the same

From high level, we want two kinds of testing:
1. testing the behavior of `init` subcommand of `packages/agoric-cli` in `agoric-sdk` repo
    1. so that we have test coverage even if the behavior of `init` subcommand changed in a PR in the future
    2. this is https://github.com/Agoric/agoric-sdk/issues/8381 and is done
3. testing the behavior of `init` subcommand of https://www.npmjs.com/package/agoric, i.e. the agoric-cli that's published to npmjs.com
    1. so that the workflow as documented in https://docs.agoric.com/guides/getting-started/ is working for developers reading this doc
    2. this is #48(this issue) and is not yet prioritized

Ref: https://github.com/Agoric/agoric-sdk/pull/8829#discussion_r1522035527

---
Edit by @LuqiPan

**Comment by LuqiPan** [comment]
For reference, here's how to do it: https://github.com/Agoric/dapp-agoric-basics/pull/24
