### ISSUE TITLE
`yarn start:ui` results in blank screen 

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/dapp-offer-up#52]
```
TypeError: At intrinsics.Object.groupBy expected boolean not function
  at installSesLockdown.ts:7:1
```
<img width="1348" alt="Screenshot 2024-01-24 at 1 42 15 PM" src="https://github.com/Agoric/dapp-offer-up/assets/11021913/ba077aed-d681-4288-89bb-3777e40c981f">

## Steps to Reproduce

```bash
[clone repository or use yarn create @agoric/dapp] 

# install dependencies 
yarn

# start web app
yarn start:ui 
```

## Environment

- dapp-offer-up: 64f6e05aaceab55c632f2b848b9d2a1d096f68c2
- node: v18.18.2 (for vite dev server)
- brave: Version 1.61.114 Chromium: 120.0.6099.199
- chrome: 120.0.6099.199
- arm64 / mac

**Comment by mhofman** [comment]
See https://github.com/endojs/endo/issues/1767, fixed in latest SES.
