### ISSUE TITLE
ci does not run yarn test

### ISSUE THREAD

**Issue by dckc** [Agoric/dapp-offer-up#77]
it got dropped: https://github.com/Agoric/dapp-offer-up/pull/73/files#r1550068488

I see why:
 - [x] it invokes e2e tests without supplying relevant context
   - `yarn test --exclude '**/e2e/**'` seems to address that, but...
 - [x] the `ui/` tests hang in watch mode

cc @0xpatrickdev @rabi-siddique @LuqiPan @turadg @samsiegart

**Comment by 0xpatrickdev** [comment]
> the ui/ tests hang in watch mode

It should not run in watch mode during CI, only locally. Try `CI=true yarn test --exclude "**/e2e/**"` to simulate a CI run.

https://vitest.dev/config/#watch
