### ISSUE TITLE
Contract Always Subtracts 25 cents regardless

### ISSUE THREAD

**Issue by ghost** [Agoric/dapp-offer-up#80]
In the offer-up UI, user can offer to give any amount of IST but regardless of what they select a fixed amount of 0.25 IST is used and is subtracted from the wallet. This is perhaps intended but it creates a confusion. Maybe this should be mentioned somewhere, or we should fix the amount in the UI and not allow user to select any other amount.

**Comment by dckc** [comment]
Yes, the price is a term of the contract, fixed when the contract is started.

It is mentioned somewhere...

> Feel free to experiment with offering less than the required 0.25 IST or attemping to purchase more than three items. You'll see these offers will not be accepted.
 -- [Making an Offer](https://docs.agoric.com/guides/getting-started/#making-an-offer)

Also:

> The price of joining the game is not fixed in the source code of this contract, but rather chosen when starting an instance of the contract.
 -- [Starting a Contract Instance](https://docs.agoric.com/guides/zoe/contract-walkthru.html#starting-a-contract-instance)

Feel free to re-open this issue if this answer isn't satisfactory.

Sorry for the delay in responding.
