### ISSUE TITLE
`lower-bundle-cost` Done in `run-chain.sh` Not Needed Anymore

### ISSUE THREAD

**Issue by amessbee** [Agoric/dapp-offer-up#96]
When we start docker, we make `lower-bundle-cost` target in the newly started instance of a3p to lower the cost of bundle - this is replaying [proposal 61](https://agoric.explorers.guru/proposal/61). But it seems that latest `a3p` instance that is used in dapp-offer-up has already lowered bundle cost as expected. 
We see the following in the output when we run `agd q swingset params` (while `make -C /workspace/contract lower-bundle-cost` is commented out):

```bash
- beans: "20000000"
  key: storageByte
```

Therefore, it seems that we should remove the following in `run-chain.sh`
```bash
make -C /workspace/contract lower-bundle-cost
```
 and corresponding targets in `Makefile` and in any other scripts.

**Comment by amessbee** [comment]
@dckc If this sounds ok, I will go and fix this.

**Comment by dckc** [comment]
yes, please

**Comment by dckc** [comment]
please check whether https://github.com/Agoric/dapp-agoric-basics should get a similar update

 - https://github.com/Agoric/dapp-agoric-basics/issues/4

**Comment by dckc** [comment]
Similarly, consider applying https://github.com/Agoric/dapp-offer-up/commit/142bf9af874794a73281ce3ab49fc2522eb7d645 to dapp-agoric-basics. And dapp-orchestration-basics, if it's relevant.
